<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <groupId>se.avanoria</groupId>
    <artifactId>alarm-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <name>alarm-service</name>
    <description>alarm-service</description>

    <properties>
        <java.version>25</java.version>
        <cxf.version>4.2.3</cxf.version>
    </properties>

    <dependencies>

        <!-- Apache CXF SOAP / JAX-WS -->
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-spring-boot-starter-jaxws</artifactId>
            <version>${cxf.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <!-- Spring Boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Tests -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <!-- Generate Java classes from WSDL -->
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-codegen-plugin</artifactId>
                <version>${cxf.version}</version>

                <executions>
                    <execution>
                        <id>generate-soap-contract</id>

                        <phase>generate-sources</phase>

                        <goals>
                            <goal>wsdl2java</goal>
                        </goals>

                        <configuration>

                            <sourceRoot>
                                ${project.build.directory}/generated-sources/cxf
                            </sourceRoot>

                            <wsdlOptions>
                                <wsdlOption>
                                    <wsdl>
                                        ${project.basedir}/src/main/resources/wsdl/alarm-service.wsdl
                                    </wsdl>
                                </wsdlOption>
                            </wsdlOptions>

                        </configuration>

                    </execution>
                </executions>

            </plugin>

            <!-- Spring Boot -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

        </plugins>
    </build>

</project>