spring.application.name=alarm-service

# --------------------
# CXF / SOAP
# --------------------
cxf.path=/soap

# --------------------
# Azure SQL
# --------------------
spring.datasource.url=jdbc:sqlserver://sql-sally-nackademin.database.windows.net:1433;database=systemintegration_database;user=sqlAdmin@sql-sally-nackademin;password={};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

# --------------------
# JPA / Hibernate
# --------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# --------------------
# Alarm thresholds
# --------------------
alarm.temperature.minimum=0
alarm.temperature.maximum=30

alarm.humidity.minimum=20
alarm.humidity.maximum=80

alarm.pressure.minimum=950
alarm.pressure.maximum=1050

alarm.vibration.minimum=0
alarm.vibration.maximum=10